### ISSUE TITLE
Regarding the configuration for external PLL clock

### ISSUE THREAD

**Issue by WeiCheng14159** [strath-sdr/rfsoc_radio#12]
Hi! Thank you for providing such an informative example for researchers working in the field of SDR. I noticed that the register files for configuring the external PLL clock are located at **rfsoc_radio/xrfclk/lmk04828**. I wondered how do you generate those files? and how to change the configuration so that a higher sampling frequency can be achieved?

**Comment by dnorthcote** [comment]
Hi @WeiCheng14159,

Thank you very much for your message. I'm glad that you have found the example useful and informative.

To generate the LMX and LMK clock configuration files, you need to download a tool called TICs Pro, from Texas Instruments.

TICs Pro is a clock configuration tool for the LMX and LMK chips. It allows you to generate the register files so that you can program the chips to output a desired clock. One warning, is that this tool is fairly challenging to use, so you will need to spend some time on this.

You can obtain the download link here: https://www.ti.com/tool/TICSPRO-SW

Thanks,
David.

**Comment by WeiCheng14159** [comment]
Thanks for your response! I will give it a try.
